services:
  finance-db:
    image: postgres:latest
    container_name: finance-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance_db
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: finance-adminer
    ports:
      - 8080:8080

volumes:
  pg_data:
