services:
  finance-app:
    container_name: finance-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - finance-db
      
  finance-db:
    image: postgres:latest
    container_name: finance-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance_db
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: finance-adminer
    ports:
      - 8080:8080

volumes:
  pg_data:
